EMBEDLY_KEY: "4e4f48f422454147b45661749719a0d3"
AWS_ACCESS_KEY_ID:       "AKIAJMWYUTYI7AWNGLCQ"
AWS_SECRET_ACCESS_KEY:   "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"
AWS_S3_BUCKET:           "votasy"

development:
  MAILER_HOST: "localhost:3000"

test:
  MAILER_HOST: "localhost:3000"

production:
  MAILER_HOST: "http://votasy.herokuapp.com/"